### ISSUE TITLE
Error running the script.

### ISSUE THREAD

**Issue by qiqetes** [PS1607/mbox-to-json#7]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/mbox-to-json", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/src/main.py", line 88, in main
    df.to_json(args.output, orient="records", index="false")
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/generic.py", line 2621, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/json/_json.py", line 120, in to_json
    ).write()
      ^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/json/_json.py", line 172, in write
    return dumps(
           ^^^^^^
OverflowError: Maximum recursion level reached
```

  
I suppose you wrote this for a concrete use case, but in case you want to improve here is the error I'm receiving

**Comment by PS1607** [comment]
Hi @qiqetes could you share the steps and resources to recreate this error?

**Comment by BenLyddane** [comment]
OverflowError: Maximum recursion level reached

Same error here. 

I ran my file:  /home/ben/.local/bin/mbox-to-json "***file path***"

CSV worked, but I'm having a hard time even opening the csv file ha. 6.5gb mbox.

**Comment by PS1607** [comment]
I'll add an option in the next release to split the CSV/JSON when outputting.

**Comment by PS1607** [comment]
This has been fixed in the new release v2.0.0

Request you to please help test it and provide feedback.
